apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: blog
  name: blog
  # namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blog
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: blog
    spec:
      containers:
        - image: jandresh/blog:latest
          imagePullPolicy: Always
          name: blog
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
